# Generated by Django 5.1 on 2024-08-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_items_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
