# Generated by Django 5.1 on 2024-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
