# Generated by Django 5.1 on 2024-09-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_item_id_itemrequest_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='itemrequest',
            old_name='user',
            new_name='user_id',
        ),
    ]
