# Generated by Django 5.1 on 2024-09-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_item_itemrequest_item_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Staff',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of stock', 'Out of Stock')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='request_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='Available', max_length=20),
        ),
    ]
